version: 2.1
aliases:
  ### RUN COMMANDS
  - &clean-build
     "clean install"
orbs:
  maven: circleci/maven@0.0.8
jobs:
  build:
    executor: java-11
    steps:
      - checkout-git
      - maven/with_cache:
          steps:
            - run: *clean-build
      - persist_to_workspace:
          root:  ~/project
          paths:
            - target
            - pom.xml
            - .circleci

workflows:
  version: 2.1
  release:
    jobs:
    - build:
        name: build-release
        context: global
        filters:
          branches:
            only:
              - /helm-charts/.*/