version: 2.1
aliases:
  ### RUN COMMANDS
  - &clean-build
      "mvn clean install"
  ### GIT
  - &restore-source-code
    keys:
      - source-{{ .Branch }}-{{ .Revision }}
      - source-{{ .Branch }}
      - source-master-a

  - &save-source-code
    key: source-{{ .Branch }}-{{ .Revision }}
    paths:
      - ".git"

commands:
    checkout-git:
      steps:
        - restore_cache: *restore-source-code
        - checkout
        - save_cache: *save-source-code
orbs:
  maven: circleci/maven@0.0.8
executors:
  # Use machine-executor if you run tests inside testcontainers.
  machine-executor:
    machine: true
  java-11:
    docker:
      - image: circleci/openjdk:11-jdk
        environment:
          _JAVA_OPTIONS: -Xmx1024m
          TERM: dumb
          TZ: "/usr/share/zoneinfo/Europe/Stockholm"
  entur-cci-toolbox:
    docker:
      - image: entur/cci-toolbox:2.0

jobs:
  build:
    executor: java-11
    steps:
      - checkout-git

      - maven/with_cache:
          settings_file: .circleci/settings.xml
          steps:
            - run: *clean-build
      - persist_to_workspace:
          root:  ~/project
          paths:
            - target
            - pom.xml
            - .circleci

workflows:
  release:
    jobs:
      - build:
          name: build-release
          context: global