apiVersion: v1
data:
  application.properties: |+
    ukur.subscription.url=http://ukur.default/external/subscription
    push.baseurl=http://ukur-demo.dev/push
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}