apiVersion: v1
data:
  application.properties: |+
    ukur.subscription.url=http://ukur/external/subscription
    push.baseurl=http://ukur-demo/push
    server.port=8090
kind: ConfigMap
metadata:
  name: {{ template "ukur-demo.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}