apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.minReplicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "common.labels" . | indent 8 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
      - command:
        - /deployments/run-java.sh
        env:
        - name: TZ
          value: Europe/Oslo
        - name: JAVA_OPTIONS
          value: -server -Dspring.config.additional-location=/etc/application-config/application.properties
            -Xmx{{ .Values.resources.xmx }} -Dserver.port={{ .Values.service.internalPort }} -Dfile.encoding=UTF-8 -Drutebanken.kubernetes.namespace={{ .Release.Namespace }}
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: health/live
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: http
          protocol: TCP
        - containerPort: {{ .Values.service.internalJolokiaPort}}
          name: jolokia
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: health/ready
            port: {{ .Values.service.internalPort }}
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 20
        resources:
          limits:
            cpu: {{ .Values.resources.cpuLimit }}
            memory: {{ .Values.resources.memLimit }}
          requests:
            cpu: {{ .Values.resources.cpuRequest }}
            memory: {{ .Values.resources.memRequest }}
        volumeMounts:
        - mountPath: /etc/application-config
          name: {{ .Values.app }}
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ .Values.app }}
        name: {{ .Values.app }}