apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  maxReplicas: {{ .Values.maxReplicas }}
  minReplicas: {{ .Values.minReplicas }}
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Release.Name }}
  targetCPUUtilizationPercentage: 80 
