{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    external-dns.alpha.kubernetes.io/target: {{ .Values.ingress.loadBalancerIP }}
  name: realtime-deviations-demo-v1
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: realtime-deviations-demo-v1{{ .Values.ingress.domainName }}
      http:
        paths:
          - backend:
              serviceName: {{ template "ukur-demo.name" . }}
              servicePort: {{ .Values.service.http.externalPort }}
  {{- end }}