apiVersion: v1
name: ukur-demo
version: '1.0.4'
appVersion: 'release-1.0.4'
description: ukur-demo is something
keywords:
- ukur-demo
sources:
- https://github.com/entur/ukur-demo
maintainers:
- name: 'Team: ror'
  email: team.rutedata@entur.org
engine: gotpl
