replicas: 1


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always
resources:
  cpuLimit: 2
  memLimit: 2000Mi
  cpuRequest: 500m
  memRequest: 500Mi
  xmx: 1000m

service:
  http:
    externalPort: 80
    internalPort: 8080
ingress:
  enabled: true
  devIp: 35.195.223.29
  stagingIp: 35.195.146.93
  productionIp: 35.187.15.14
